apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  labels:
    app: boardgame-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app
          image: jayu3110/boardgame-listing:latest
          ports:
            - containerPort: 8080